### ISSUE TITLE
PRACTICA #1 DIAGRAMA DE CLASES

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-equipo-fglr#1]
[PRACTICA DIAGRAMA DE CLASES_SPRINT 4.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-equipo-fglr/files/7791158/PRACTICA.DIAGRAMA.DE.CLASES_SPRINT.4.pdf)

**Comment by Yabin-2021** [comment]
Revisado.

**Calificación - 30 %**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
